/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author afarid
 */
public class Administrateur extends javax.swing.JFrame {

  static String oldip;
    static String newip;
    public Administrateur() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(92, 84, 76));
        jPanel1.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 10);

        jPanel2.setBackground(new java.awt.Color(152, 137, 123));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(null);

        jButton6.setText("jButton6");
        jPanel2.add(jButton6);
        jButton6.setBounds(80, 140, 94, 25);

        jButton7.setText("utilisateur");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(230, 10, 150, 30);

        jButton8.setText("Configuration");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(440, 10, 140, 30);

        jButton11.setText("Test");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton11);
        jButton11.setBounds(650, 10, 140, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 1050, 50);

        jPanel3.setBackground(new java.awt.Color(92, 84, 76));
        jPanel3.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 40, 1050, 10);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(1038, 110, 10, 720);

        jPanel5.setBackground(new java.awt.Color(152, 137, 123));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(230, 100, 30));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 96, 18));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Application de simulation du fonctionnement d'un ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(272, 5, 362, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 243, 243));
        jLabel7.setText(" IDS");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(639, 5, 28, 18);

        jLabel8.setForeground(new java.awt.Color(233, 80, 15));
        jLabel8.setText("_");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(672, 5, 6, 15);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 247, 247));
        jLabel9.setText(" SNORT");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(684, 5, 54, 18);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 10, 1050, 40);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 110, 1030, 10);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(10, 830, 1030, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(10, 110, 10, 720);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("le mode IDS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, 440, 130, 30);

        jPanel4.setBackground(new java.awt.Color(152, 137, 123));
        jPanel4.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "renifleur de paquets", "capture de paquets", "IDS" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(520, 10, 180, 30);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("choisir le mode fonctionnement de SNORT              :");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(30, 10, 430, 30);

        jButton2.setText("valider");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(780, 10, 120, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(20, 220, 1010, 60);
        getContentPane().add(jPanel6);
        jPanel6.setBounds(540, 400, 290, 0);

        jPanel7.setBackground(new java.awt.Color(92, 84, 76));
        jPanel7.setForeground(new java.awt.Color(102, 102, 102));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(10, 280, 1030, 10);

        jPanel11.setBackground(new java.awt.Color(92, 84, 76));
        getContentPane().add(jPanel11);
        jPanel11.setBounds(10, 210, 1030, 10);

        jPanel15.setBackground(new java.awt.Color(92, 84, 76));
        getContentPane().add(jPanel15);
        jPanel15.setBounds(990, 220, 50, 60);

        jPanel8.setBackground(new java.awt.Color(92, 84, 76));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(10, 220, 40, 60);

        jLabel4.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Bienvenue sur le compte administrateur");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 140, 420, 30);

        jLabel5.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("le mode renifleur de paquets");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 440, 320, 30);

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("le mode de cature des paquets");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(690, 440, 330, 30);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(380, 490, 10, 320);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(430, 480, 120, 20);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(610, 490, 10, 320);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(20, 480, 320, 10);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(660, 480, 330, 10);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("les paquets et les enregistrer avec ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(670, 570, 330, 30);

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel14.setText("contrôle de la quantité d’information");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(660, 600, 330, 30);

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel15.setText("en utilisant une organisation hiérarchique.");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(640, 660, 370, 30);

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel17.setText("Le mode Capture permet de capturer");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(660, 540, 318, 30);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel11.setText("d’écouter tout le trafic circulant sur le");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 580, 330, 30);

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel16.setText("réseau et de l’afficher dans notre");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 610, 330, 30);

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel18.setText("                 application");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(60, 640, 310, 30);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel19.setText("Le mode Renifleur de Paquets permet");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 550, 326, 30);

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel20.setText("dans le répertoire des fichiers journaux");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(650, 630, 340, 30);

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel21.setText("utilisé en mode IDS");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(410, 580, 180, 15);

        jLabel22.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel22.setText("il permet la détection");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(400, 600, 200, 30);

        jLabel23.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel23.setText("un message d’alert.");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(410, 670, 200, 40);

        jLabel24.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel24.setText("temps réel et de générer");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(390, 650, 220, 30);

        jLabel25.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel25.setText("Lorsque Snort est ");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(410, 550, 170, 21);

        jLabel26.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel26.setText("d’intrusion presque en");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(400, 630, 200, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
       
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        if (jComboBox1.getSelectedItem()=="renifleur de paquets"){
        Renifleur_de_paquets h= new Renifleur_de_paquets();
                h.setVisible(true);}
       if (jComboBox1.getSelectedItem()=="capture de paquets"){
        Capture_de_paquets p= new Capture_de_paquets();
                p.setVisible(true);}
       if(jComboBox1.getSelectedItem()=="IDS"){
        IDS k= new IDS();
                k.setVisible(true);}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       Configuration l= new Configuration();
               l.setVisible(true);
               dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         Utilisateur v= new Utilisateur();
               v.setVisible(true);
                       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
      Test l= new Test();
               l.setVisible(true);
                       dispose();
    }//GEN-LAST:event_jButton11ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrateur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrateur().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
