/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author afarid
 */
public class Capture_de_paquets extends javax.swing.JFrame {
String l="";
    /**
     * Creates new form Capture_de_paquets
     */
    public Capture_de_paquets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(null);

        jPanel4.setBackground(new java.awt.Color(92, 84, 76));
        jPanel4.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1050, 10);

        jPanel6.setBackground(new java.awt.Color(152, 137, 123));
        jPanel6.setAlignmentX(0.0F);
        jPanel6.setAlignmentY(0.0F);
        jPanel6.setLayout(null);

        jButton7.setText("jButton6");
        jPanel6.add(jButton7);
        jButton7.setBounds(80, 140, 94, 25);

        jButton.setText("retour");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });
        jPanel6.add(jButton);
        jButton.setBounds(40, 10, 79, 25);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 50, 1050, 40);

        jPanel7.setBackground(new java.awt.Color(92, 84, 76));
        jPanel7.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, 40, 1050, 10);

        jPanel8.setBackground(new java.awt.Color(152, 137, 123));
        jPanel8.setAlignmentX(0.0F);
        jPanel8.setAlignmentY(0.0F);
        jPanel8.setLayout(null);

        jLabel10.setBackground(new java.awt.Color(230, 100, 30));
        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(237, 96, 18));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Application de simulation du fonctionnement d'un ");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel8.add(jLabel10);
        jLabel10.setBounds(272, 5, 362, 18);

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(245, 243, 243));
        jLabel11.setText(" IDS");
        jPanel8.add(jLabel11);
        jLabel11.setBounds(639, 5, 28, 18);

        jLabel12.setForeground(new java.awt.Color(233, 80, 15));
        jLabel12.setText("_");
        jPanel8.add(jLabel12);
        jLabel12.setBounds(672, 5, 6, 15);

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(249, 247, 247));
        jLabel13.setText(" SNORT");
        jPanel8.add(jLabel13);
        jLabel13.setBounds(684, 5, 54, 18);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(0, 10, 1050, 40);
        getContentPane().add(jSeparator8);
        jSeparator8.setBounds(20, 740, 1010, 10);

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(1030, 170, 10, 570);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 170, 10, 570);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Afficher le fichier de la capture                                           :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 500, 450, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Lancer  une capture actuelle");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 390, 270, 20);

        jButton1.setText("Commencer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(750, 460, 140, 30);

        jButton2.setText("Afficher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(750, 500, 140, 30);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lancer la capture des paquets                                             :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 460, 450, 30);
        getContentPane().add(jSeparator9);
        jSeparator9.setBounds(290, 380, 440, 10);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 540, 660, 170);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(750, 420, 140, 30);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Afficher les paquets déja capturé          :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 180, 350, 30);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("saisir le nombre de paquet que vous voulez caturer :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 420, 460, 30);

        jButton3.setText("Afficher");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(750, 190, 140, 30);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(190, 240, 660, 120);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(540, 440, 50, 10);
        getContentPane().add(jSeparator10);
        jSeparator10.setBounds(20, 170, 1010, 10);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Bienvenue dans le mode Capture de paquets");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 120, 400, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        Administrateur l= new Administrateur();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "veuiez  SVP saisir le nombre de paquet que vous voulez capturer");}
        else{
        try{
            Process p= Runtime.getRuntime().exec("snort -b -n "+jTextField1.getText()+" -l /var/log/snort/ ");
            try {
    Thread.sleep(12000);                 //1000 milliseconds is one second.
} catch(InterruptedException ex) {
    Thread.currentThread().interrupt();
}
            JOptionPane.showMessageDialog(this, "La capture est terminer");
           }
        catch(IOException e){
            System.out.println("exception happened - here's what I know: ");
            e.printStackTrace();
        }}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String s = null;
        try{
            
            //Run the process
 //Process p= Runtime.getRuntime().exec("cat /home/fich");           
 Process p= Runtime.getRuntime().exec("ls /var/log/snort/");
            //Get the input stream
            BufferedReader stdInput = new BufferedReader(new
                 InputStreamReader(p.getInputStream()));
 
            BufferedReader stdError = new BufferedReader(new
                 InputStreamReader(p.getErrorStream()));


             while ((s = stdInput.readLine()) != null) {
                 
                 
            
               l=s;
            }
              while ((s = stdError.readLine()) != null) {
                System.out.println(s);
            }
             

            
            }
        catch(IOException e){
            System.out.println("somthing goes wrong: ");
            e.printStackTrace();
           // System.exit(-1);
        }
        
         String w = null;
        try{
            
            //Run the process
 //Process p= Runtime.getRuntime().exec("cat /home/fich");           
 Process q= Runtime.getRuntime().exec("tcpdump -r /var/log/snort/"+l);
            //Get the input stream
            BufferedReader stdInput = new BufferedReader(new
                 InputStreamReader(q.getInputStream()));
 
            BufferedReader stdError = new BufferedReader(new
                 InputStreamReader(q.getErrorStream()));


             while ((w = stdInput.readLine()) != null) {
                 
                 
            
                  jTextArea1.append(w+"\n");
   
                 jTextArea1.update(jTextArea1.getGraphics());
                 System.out.println(w);
          
         
            }
              while ((w = stdError.readLine()) != null) {
                System.out.println(w);
            }
             

            
            }
        catch(IOException e){
            System.out.println("somthing goes wrong: ");
            e.printStackTrace();
           // System.exit(-1);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           String s = null;
        try{
            jTextArea2.setText("");
            //Run the process
 //Process p= Runtime.getRuntime().exec("cat /home/fich");           
 Process p= Runtime.getRuntime().exec("/var/log/snort/affiche.bat");
            //Get the input stream
            BufferedReader stdInput = new BufferedReader(new
                 InputStreamReader(p.getInputStream()));
 
            BufferedReader stdError = new BufferedReader(new
                 InputStreamReader(p.getErrorStream()));


             while ((s = stdInput.readLine()) != null) {
                 
                 
            
                  jTextArea2.append(s+"\n");
   
                 jTextArea2.update(jTextArea2.getGraphics());
                 System.out.println(s);
               
            }
              while ((s = stdError.readLine()) != null) {
                System.out.println(s);
            }
             

            
            }
        catch(IOException e){
            System.out.println("somthing goes wrong: ");
            e.printStackTrace();
           // System.exit(-1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capture_de_paquets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capture_de_paquets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capture_de_paquets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capture_de_paquets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capture_de_paquets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
