/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import static Interface.Administrateur.newip;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class Configuration extends javax.swing.JFrame {
static String oldip1,oldip2,oldip3,oldip4,oldip5,oldip6;
    static String newip1,newip2,newip3,eth3,s;
    public Configuration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1050, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(92, 84, 76));
        jPanel1.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1050, 10);

        jPanel2.setBackground(new java.awt.Color(152, 137, 123));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(null);

        jButton6.setText("jButton6");
        jPanel2.add(jButton6);
        jButton6.setBounds(80, 140, 94, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 1050, 20);

        jPanel3.setBackground(new java.awt.Color(92, 84, 76));
        jPanel3.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 40, 1050, 10);

        jPanel5.setBackground(new java.awt.Color(152, 137, 123));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(230, 100, 30));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 96, 18));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Application de simulation du fonctionnement d'un ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(272, 5, 362, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 243, 243));
        jLabel7.setText(" IDS");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(639, 5, 28, 18);

        jLabel8.setForeground(new java.awt.Color(233, 80, 15));
        jLabel8.setText("_");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(672, 5, 6, 15);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 247, 247));
        jLabel9.setText(" SNORT");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(684, 5, 54, 18);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 10, 1050, 40);

        jLabel2.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("La Configuration De Snort");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 90, 300, 30);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("saisir le nom  de vôtre interface                                      :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 330, 430, 40);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(700, 330, 180, 30);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("saisir l'@IP du réseau que vous voullez sécuriser :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 180, 430, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(700, 190, 180, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("spécifier le chemin des régles  de snort                     :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 260, 430, 40);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(700, 260, 180, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(20, 580, 1010, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(20, 130, 10, 450);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(1030, 130, 10, 450);

        jButton2.setText("Retour");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(230, 490, 110, 30);

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 490, 110, 30);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 130, 1010, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")){
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "veuiez  SVP saisir l'@IP du réseau");}
 if(jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this, "veuiez  SVP saisir le chemin des régles  de snort");}
 if(jTextField3.getText().equals("")){
            JOptionPane.showMessageDialog(this, "veuiez  SVP saisir le nom de vôtre interface");}}
        else{
        newip1=jTextField1.getText();
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader = new BufferedReader(new FileReader(file));
             BufferedReader reader1 = new BufferedReader(new FileReader(file));
             String line1 = "", oldtext1 = "";
             int i=0;
             while((line1 = reader.readLine()) != null)
                 {
                 oldtext1 += line1 + "\r\n";
             }
             
          while((line1 = reader1.readLine()) != null)
                 {
                     
                 if(i==44){
                     String [] lin =line1.split(" ");
                     oldip1=lin[2];
                     break;}
                 i++;
             }
           
             String newtext = oldtext1.replaceAll(oldip1, newip1);
            
             FileWriter writer = new FileWriter("/etc/snort/snort.conf");
             writer.write(newtext);writer.close();
             reader.close();reader1.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }   
         newip2=jTextField2.getText();
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader2 = new BufferedReader(new FileReader(file));
             BufferedReader reader3 = new BufferedReader(new FileReader(file));
             String line2 = "", oldtext2 = "";
             int j=0;
             while((line2 = reader2.readLine()) != null)
                 {
                 oldtext2 += line2 + "\r\n";
             }
             
          while((line2 = reader3.readLine()) != null)
                 {
                     
                 if(j==103){
                     String [] lin1 =line2.split(" ");
                     oldip2=lin1[2];
                     break;}
                 j++;
             }
           
             String newtext2 = oldtext2.replaceAll(oldip2, newip2+"/rules");
            
             FileWriter writer2 = new FileWriter("/etc/snort/snort.conf");
             writer2.write(newtext2);writer2.close();
             reader2.close();reader3.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }   
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader4 = new BufferedReader(new FileReader(file));
             BufferedReader reader5 = new BufferedReader(new FileReader(file));
             String line3 = "", oldtext3 = "";
             int k=0;
             while((line3 = reader4.readLine()) != null)
                 {
                 oldtext3 += line3 + "\r\n";
             }
             
          while((line3 = reader5.readLine()) != null)
                 {
                     
                 if(k==104){
                     String [] lin2 =line3.split(" ");
                     oldip3=lin2[2];
                     break;}
                 k++;
             }
           
             String newtext3 = oldtext3.replaceAll(oldip3, newip2+"/so_rules");
            
             FileWriter writer3 = new FileWriter("/etc/snort/snort.conf");
             writer3.write(newtext3);writer3.close();
             reader4.close();reader5.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader6 = new BufferedReader(new FileReader(file));
             BufferedReader reader7 = new BufferedReader(new FileReader(file));
             String line4 = "", oldtext4 = "";
             int l=0;
             while((line4 = reader6.readLine()) != null)
                 {
                 oldtext4 += line4 + "\r\n";
             }
             
          while((line4 = reader7.readLine()) != null)
                 {
                     
                 if(l==105){
                     String [] lin3 =line4.split(" ");
                     oldip4=lin3[2];
                     break;}
                 l++;
             }
           
             String newtext4 = oldtext4.replaceAll(oldip4, newip2+"/preproc_rules");
            
             FileWriter writer4 = new FileWriter("/etc/snort/snort.conf");
             writer4.write(newtext4);writer4.close();
             reader6.close();reader7.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader8 = new BufferedReader(new FileReader(file));
             BufferedReader reader9 = new BufferedReader(new FileReader(file));
             String line5 = "", oldtext5 = "";
             int m=0;
             while((line5 = reader8.readLine()) != null)
                 {
                 oldtext5 += line5+ "\r\n";
             }
             
          while((line5 = reader9.readLine()) != null)
                 {
                     
                 if(m==112){
                     String [] lin4 =line5.split(" ");
                     oldip5=lin4[2];
                     break;}
                 m++;
             }
           
             String newtext5 = oldtext5.replaceAll(oldip5, newip2+"/rules/iplists");
            
             FileWriter writer5 = new FileWriter("/etc/snort/snort.conf");
             writer5.write(newtext5);writer5.close();
             reader8.close();reader9.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader10 = new BufferedReader(new FileReader(file));
             BufferedReader reader11 = new BufferedReader(new FileReader(file));
             String line6 = "", oldtext6 = "";
             int m=0;
             while((line6 = reader10.readLine()) != null)
                 {
                 oldtext6 += line6+ "\r\n";
             }
             
          while((line6 = reader11.readLine()) != null)
                 {
                     
                 if(m==113){
                     String [] lin4 =line6.split(" ");
                     oldip6=lin4[2];
                     break;}
                 m++;
             }
           
             String newtext6 = oldtext6.replaceAll(oldip6, newip2+"/rules/iplists");
            
             FileWriter writer6 = new FileWriter("/etc/snort/snort.conf");
             writer6.write(newtext6);writer6.close();
             reader10.close();reader11.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         }
         /*newip2=jTextField2.getText();
         try
             {
             File file = new File("/etc/snort/snort.conf");
             BufferedReader reader2 = new BufferedReader(new FileReader(file));
             BufferedReader reader3 = new BufferedReader(new FileReader(file));
             String line2 = "", oldtext2 = "";
             int i=0;
             while((line2 = reader2.readLine()) != null)
                 {
                 oldtext2 += line2+ "\r\n";
             }
             
          while((line2 = reader3.readLine()) != null)
                 {
                     
                 if(i==103){
                     String [] lin1 =line2.split(" ");
                     oldip2=lin1[2];
                     }
                 if(i==104){
                     String [] lin2 =line2.split(" ");
                     oldip3=lin2[2];
                     }
                 if(i==105){
                     String [] lin3 =line2.split(" ");
                     oldip4=lin3[2];
                     }
                 i++;
             }
           
             String newtext1 = oldtext2.replaceAll(oldip2, newip2+"/rules");
             String newtext2 = oldtext2.replaceAll(oldip3, newip2+"/so_rules");
            String newtext3 = oldtext2.replaceAll(oldip4, newip2+"/preproc_rules");
             FileWriter writer1 = new FileWriter("/etc/snort/snort.conf");
             FileWriter writer2 = new FileWriter("/etc/snort/snort.conf");
             FileWriter writer3 = new FileWriter("/etc/snort/snort.conf");
             writer1.write(newtext1);writer2.write(newtext2); writer3.write(newtext3); writer1.close();
             writer2.close();writer3.close();
             reader2.close();reader3.close();
         }
         catch (IOException ioe)
             {
             ioe.printStackTrace();
         } */ 
          eth3=jTextField3.getText();
         String s = null;
        try{
           Process p= Runtime.getRuntime().exec("snort -i "+eth3);
            }
        catch(IOException e){
            System.out.println("exception happened - here's what I know: ");
            e.printStackTrace();
           
        }
        
           JOptionPane.showMessageDialog(this, "vôtre fivhier de configuration SNORT a été bien configuré ");
        
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Administrateur l= new Administrateur();
               l.setVisible(true);
                       dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Configuration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
