
package Interface;

import BDD.BDD;
import BDD.parameter;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {
ResultSet rs;
    BDD db;
    String username1, password1, hak;
    public Login() {
         db = new BDD(new parameter().HOST_DB, new parameter().USERNAME_DB,new parameter().PASSWORD_DB, new parameter().IPHOST, new parameter().PORT);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Valider = new javax.swing.JButton();
        Valider1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 640));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("password :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 360, 143, 32);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("UserName :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 270, 143, 32);

        txt_username.setText("afarid");
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username);
        txt_username.setBounds(580, 270, 170, 40);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Login");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 100, 70, 40);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(510, 460, 160, 40);

        Valider1.setText("fermer");
        Valider1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valider1ActionPerformed(evt);
            }
        });
        getContentPane().add(Valider1);
        Valider1.setBounds(280, 460, 150, 40);

        jPanel1.setBackground(new java.awt.Color(92, 84, 76));
        jPanel1.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 10);

        jPanel2.setBackground(new java.awt.Color(152, 137, 123));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setLayout(null);

        jButton6.setText("jButton6");
        jPanel2.add(jButton6);
        jButton6.setBounds(80, 140, 94, 25);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 50, 950, 20);

        jPanel3.setBackground(new java.awt.Color(92, 84, 76));
        jPanel3.setForeground(new java.awt.Color(64, 40, 40));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 40, 950, 10);

        jPanel5.setBackground(new java.awt.Color(152, 137, 123));
        jPanel5.setAlignmentX(0.0F);
        jPanel5.setAlignmentY(0.0F);
        jPanel5.setLayout(null);

        jLabel6.setBackground(new java.awt.Color(230, 100, 30));
        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(237, 96, 18));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Application de simulation du fonctionnement d'un ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel5.add(jLabel6);
        jLabel6.setBounds(272, 5, 362, 18);

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(245, 243, 243));
        jLabel7.setText(" IDS");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(639, 5, 28, 18);

        jLabel8.setForeground(new java.awt.Color(233, 80, 15));
        jLabel8.setText("_");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(672, 5, 6, 15);

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(249, 247, 247));
        jLabel9.setText(" SNORT");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(684, 5, 54, 18);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 10, 950, 40);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(20, 600, 900, 10);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 150, 10, 450);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator6);
        jSeparator6.setBounds(920, 150, 10, 450);
        getContentPane().add(jSeparator7);
        jSeparator7.setBounds(20, 150, 900, 10);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel4.setText("veuillez SVP entrer vôtre nom d'utilisateur et vôtre mot de passe :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 580, 30);

        txt_password.setText("snort");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password);
        txt_password.setBounds(580, 350, 170, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Valider1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valider1ActionPerformed
       dispose();
    }//GEN-LAST:event_Valider1ActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
     rs = db.querySelectAll("utilisateur", "username='" + txt_username.getText() + "' and password='" + txt_password.getText() + "'");
        try {
            while (rs.next()) {
                username1 = rs.getString("username");
                password1 = rs.getString("password");
                hak = rs.getString("type");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (username1 == null && password1 == null) {
            JOptionPane.showMessageDialog(this, "le nom utilisateur ou le mots de pass est incorrect");
        } else {
            if (hak.equals("admin")) {
                Administrateur h= new Administrateur();
                h.setVisible(true);
                this.dispose();
            } else {
                Technicien k = new Technicien();
                k.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Valider;
    private javax.swing.JButton Valider1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
